# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Updated to use BrowserStack CORE team approved base images
# syntax=docker/dockerfile:1.4

# Build stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install Node.js, npm, and git on Alpine base
RUN apk add --no-cache git

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# Clone specific branch and sparse checkout src directory
RUN git clone -b local-mcp-changes https://github.com/ruturaj-browserstack/mcp-server.git

# Build the cloned repository
WORKDIR /app/mcp-server
RUN npm ci --ignore-scripts
RUN npm run build

# Return to main app directory and build main project
WORKDIR /app
# Copy source and build
COPY . .
RUN npm run build

# Production stage
FROM node:lts-alpine AS runtime
WORKDIR /app

# Set environment variable
ENV REMOTE_MCP='true'

# Copy built artifacts and production dependencies
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/mcp-server ./mcp-server
COPY package.json package-lock.json ./

# Install production dependencies for main app
RUN npm ci --only=production --ignore-scripts

# Install production dependencies for the mcp-server package
WORKDIR /app/mcp-server
RUN npm ci --only=production --ignore-scripts

# Return to main directory and install the local mcp-server package
WORKDIR /app
RUN npm install ./mcp-server

# Default command to start the MCP server
ENTRYPOINT ["node", "dist/index.js"]
