# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Updated to use BrowserStack CORE team approved base images
# syntax=docker/dockerfile:1.4

# Build stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install Node.js, npm, and git on Alpine base
RUN apk add --no-cache git

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

# Clone specific branch and sparse checkout src directory
RUN git clone --depth 1 --filter=blob:none --sparse -b local-mcp-changes https://github.com/ruturaj-browserstack/mcp-server.git temp && \
    cd temp && \
    git sparse-checkout set src && \
    mv src ../src/lib && \
    cd .. && \
    rm -rf temp

# Copy source and build
COPY . .
RUN npm run build

# Production stage
FROM node:lts-alpine AS runtime
WORKDIR /app

# Copy built artifacts and production dependencies
COPY --from=builder /app/dist ./dist
COPY package.json package-lock.json ./
RUN npm ci --only=production --ignore-scripts

# Default command to start the MCP server
ENTRYPOINT ["node", "dist/index.js"]
